name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  node-test:
    name: Node test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Pnpm install
        run: pnpm install

      - name: Type check
        run: |
          pnpm type-check

      - name: Test
        run: |
          pnpm test